### ISSUE TITLE
tour: Lado com textos sem se adaptar à tela

### ISSUE THREAD

**Issue by LuccaPrado** [dgv/go-tour-br#20]
Contexto: https://go-tour-br.appspot.com/basics/1

No lado esquerdo das páginas, o texto não está responsivo, então acaba entrando embaixo da parte de editor de código, fazendo ser possível ver a frase completa só se der um zoom out

**Comment by gerep** [comment]
@LuccaPrado pode dizer como você fez? Acabei de verificar e para mim aparece tudo OK. Se tiver como mandar um print também.

**Comment by LuccaPrado** [comment]
![image](https://user-images.githubusercontent.com/8813731/46314502-1eaf1f80-c5a1-11e8-9c12-d81f2f976c2c.png)
@gerep, ele está ficando como na imagem acima tanto no chrome quanto no firefox, enquanto o original, vide img abaixo, está responsivo.

![image](https://user-images.githubusercontent.com/8813731/46314861-16a3af80-c5a2-11e8-8ff0-1e00124cc370.png)

Dando uma comparada no CSS do original e na traduzida, parece que é por que nessa está 60% e na original 50% como mostrado abaixo

Atual traduzida 
https://github.com/golangbr/go-tour-br/blob/30fc496b3a6bcbf8325d104392ad5855b3e20d5f/static/css/app.css#L302


[Mirror do Tour Oficial](https://github.com/golang/tour/blob/d642b9371986f5bb2152547a0d525a57f634c3ef/static/css/app.css#L303)

**Comment by gerep** [comment]
Agora eu entendi @LuccaPrado, quando abre a página já está com problema mas quando começo a movimentar a barra, o texto se ajusta como deveria.

Vai fazer um PR? =)

**Comment by LuccaPrado** [comment]
@gerep Com certeza, apenas esperando o Fds :)

**Comment by gerep** [comment]
@LuccaPrado rapaz, já faz um tempinho hein? haha

Ainda consegue enviar a correção?

**Comment by LuccaPrado** [comment]
Pultz, acabei me esquecendo kkk
Vou ver se ainda tenho no Pc e abro, finalmente, a PR

**Comment by LuccaPrado** [comment]
Trabalhando nisso!
