### ISSUE TITLE
tour: Chamada incorreta de método e Letra maiúscula indevida

### ISSUE THREAD

**Issue by MotaOcimar** [dgv/go-tour-br#32]
Contexto: https://go-tour-br.appspot.com/methods/6
São duas correções: 

1. Em
> Comparando os dois programas anteriores, você pode notar que funções com um argumento de ponteiro deve ter um ponteiro:
> ```go
> var v Vertex
> ScaleFunc(v)  // Erro de compilação!
> ScaleFunc(&v) // OK
> ```

```ScaleFunc``` deve receber um segundo argumento com o valor de escala. Corrigindo ficaria:
> Comparando os dois programas anteriores, você pode notar que funções com um argumento de ponteiro deve ter um ponteiro:
> ```go
> var v Vertex
> ScaleFunc(v, 5)  // Erro de compilação!
> ScaleFunc(&v, 5) // OK
> ```

2. Em
> Para a instrução ```v.Scale(5)``` , embora ```V``` seja um valor e não um ponteiro, o método com o receptor ponteiro é chamado automaticamente. Ou seja, por conveniência, Go interpreta a declaração ```v.Scale(5)``` como ```(&V).Scale(5)``` uma vez que o método Scale tem um receptor de ponteiro.

```v``` deve aparecer minúsculo tanto em "[...] embora ```V``` seja [...]" quanto na expressão ```(&V).Scale(5)```.

**Comment by gerep** [comment]
Olá @MotaOcimar, você pode abrir um PR com as correções?
