### ISSUE TITLE
tour: Provável erro de digitação

### ISSUE THREAD

**Issue by AndreReliquias** [dgv/go-tour-br#39]
Contexto: https://go-tour-br.appspot.com/basics/13

No seguinte trecho:

> Diferente de C, em Go atribuição entre os itens de tipo diferente requer uma conversão explícita. Tente remover as conversões float64 ou int no exemplo e veja o que acontece.

Não seria para remover a conversão de `uint` ao invés de `int`? Já que as conversões realizadas no código foram:

```
	var f float64 = math.Sqrt(float64(x*x + y*y))
	var z uint = uint(f)
```

**Comment by dgv** [comment]
Sim, obrigado, desculpe a demora..
